meta:
  engine: 4.1.0
units:
  kx: u
  ky: U
  px: kx + 5
  py: ky + 5
points: 
  zones:
    matrix:
      # Fix placement on KiCAD sheet.
      anchor:
        shift: [100, -100]
      key:
        padding: 1ky
        spread: 1kx
      columns:
        pinky:
          key:
            stagger: 17
        ring:
          key:
            stagger: 17
        middle:
          key:
            stagger: 11
        index:
          key:
            stagger: -15
        inner:
      rows:
        bottom:
        home:
        top:
    thumbs:
      key:
        padding: 1py
        spread: 1px
        splay: -10
      anchor:
        ref: matrix_inner_bottom
        shift: [-0.5kx, -1ky - 3] 
      columns:
        left:
        middle:
        right:
      rows:
        cluster:
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]
  board:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_pinky_top
          shift: [-0.5px,0.5py + 23]
        - ref: matrix_middle_top
          shift: [-0.5px,0.5py - 5]
        - ref: matrix_middle_top
          shift: [-0.5px,0.5py]
        - ref: matrix_middle_top
          shift: [0.5px,0.5py]
        - ref: matrix_middle_top
          shift: [0.5px,0.5py - 5]
        - ref: matrix_inner_top
          shift: [0.5px + 20.5, 0.5py + 10]
        - ref: thumbs_right_cluster
          shift: [-0.5px, 0.5py]
        - ref: thumbs_right_cluster
          shift: [0.5px, 0.5py]
        - ref: thumbs_right_cluster
          shift: [0.5px, -0.5py]
        - ref: thumbs_middle_cluster
          shift: [0.5px, -0.5py]
        - ref: thumbs_middle_cluster
          shift: [0.5px, -0.5py]
        - ref: thumbs_left_cluster
          shift: [0.5px,-0.5py]
        - ref: matrix_pinky_bottom
          shift: [-0.5px,-0.5py - 10.7]
      fillet: 2
  combo:
    - name: board
    - operation: subtract
      name: keys

pcbs:
  pineapple:
    outlines:
      main:
        outline: board
    footprints:
      mx_hotswap:
        what: mx
        where: true 
        params:
          keycaps: true 
          reverse: true 
          hotswap: true 
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      promicro:
        what: promicro
        params:
          orientation: "down"
        where:
          ref: matrix_inner_top
          shift: [1px - 2.5, 0]
          rotate: -90
      reset:
        what: button
        params:
          from: GND
          to: RST
        where:
          ref: matrix_inner_top
          shift: [0.5px - 6, 0.75py - 3]
          rotate: -90
      jstph:
        what: jstph
        params:
          side: 'B'
          pos: ''
          neg: ''
        where:
          ref: matrix_ring_bottom
          shift: [0, 1py]
          rotate: 0
